### ISSUE TITLE
icon for Back button missing

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#85]
see [https://jem4.datenablage.info/images/clips/back-button.mov](https://jem4.datenablage.info/images/clips/back-button.mov)

Use the css class "icon-chevron-left"

**Comment by jojo12** [comment]
2.3.8 is fixed (sometimes in the second line on the left side!

**Comment by Heklaterriol** [comment]
but the icon is still missing
![th](https://user-images.githubusercontent.com/28540581/219109998-e04ef2ad-0395-4d2a-b786-412aa44fd545.jpg)
